name: Build and deploy documentation

on: 
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu:20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: make mkdocs-material
      - run: make mkdocs-plugins
      - run: mkdocs gh-deploy --force
