name: Download, pack and publish all main deps

on:
  workflow_dispatch

jobs:
  dl:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make camera-debug-facility_defconfig
      - run: make -C output/camera-debug-facility
      - run: make pack-dl
